### PR TITLE
get lastet known working spec for cfndsl during docker build

### PR DESCRIPTION
**Pull request by Guslington**

### CODE REVIEW

**Comment by aaronwalker** [comment]
@Guslington seem this build failed due to github rate limit. downloading the component repos. We might want to add some soft of backoff in the test scripts

**Comment by Guslington** [comment]
@aaronwalker yeah for sure, these tests will change anyway once we have more components with test cases.

**Comment by toshke** [comment]
@Guslington @Guslington problem with Github rate limit is we can't have any secrets stored in Travis PR builds - perhaps we could solve this with Azure Devops portal, as it is free for open source projects - https://azure.microsoft.com/en-au/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

**Comment by Guslington** [comment]
@toshke haha even for AWS cloudformation template dsl's?

**Comment by toshke** [comment]
@Guslington you would be surprised. There is actually plugin to deploy directly to amazon from Azure Devops portal - https://github.com/aws/aws-vsts-tools

**Comment by Guslington** [comment]
@toshke lol! I'll take a look

**Pull request merged**
