### PR TITLE
Cfndsl 1.0 and <1 compatibility

### PR DESCRIPTION
**Pull request by toshke**
## What

This PR relates to #138 and enables cfhighlander to support work with  both with version <1 and ~1 of `cfndsl` gem. While gemspec has bumped the version to cfndsl to ~1,  gem version can vary on the actual execution environment, depending on installation method. 

Relates to 
https://github.com/theonestack/cfhighlander/issues/121
https://github.com/theonestack/cfhighlander/pull/136
https://github.com/theonestack/cfhighlander/pull/138

## How

[cfndsl](https://github.com/cfndsl/cfndsl) introduced breaking change that all variables injected from external YAML files are available through `external_parameters` map. Depending on loaded version of cfndsl gem, cfndsl template rendered by cfhighlander will either
- just consume all variables as part of the binding if cfndsl version is < 1
- inject all variables as part of the binding if cfndsl version ~1, by extracting them from `external_parameters` var

This method implementation is backward compatible and does not require template developers to change anything in their templates. 

## Testing

```
make test
```
https://travis-ci.com/toshke/cfhighlander/builds/149348586

Travis build one theonestack org is failing due GitHub rate limiting, I had to commit empty commit to rebuild, as PR rebuilds seem to be disallowed now. 

## Future enhancements

As this can be stop/gap solution, this feature can be turned off in future versions by default, while in current version it could be turned off via syntax below (or similar), @aaronwalker  looking forward to any suggestions you may have on this one, but it would be at least 2 year period until we could turn off this legacy support by default, while all the components are migrated. Also, once turned off, we coudl think of how to notify the user of need to migrate to use of `external_parameters` 

```ruby
CfhighlanderTemplate do
     LegacyCfndslBindings false
done
```

### CODE REVIEW

**Comment by Guslington** [comment]
@toshke looks good to me, i'll test it out with #138. 

In terms of distribution we could package the docker container with both cfndsl `0.17.3` and `1.0` but it if users are relying on the gem for dependencies the user may have to manually install their version of cfndsl.

The other issue will be the spec file as the last known working version for `0.17.3` is `9.0.0`. It'll all depend on what version the component requires, maybe we need a provision to supply a spec version on a component?

**Comment by toshke** [comment]
1. 
@Guslington  in terms of #138 , this PR actually supersedes it, as keys for lambdas will be converted to external_parameters out of the box. E.g, testing with `cognito` component, gives following cfndsl template (just part of the template below)

```

CloudFormation do
  # cfhl meta: cfndl_version=1.0.1
  pool_name = external_parameters.fetch(:pool_name, nil)
  alias_attributes = external_parameters.fetch(:alias_attributes, nil)
  default_client = external_parameters.fetch(:default_client, nil)
  default_user_group = external_parameters.fetch(:default_user_group, nil)
  user_schema = external_parameters.fetch(:user_schema, nil)
  clients = external_parameters.fetch(:clients, nil)
  groups = external_parameters.fetch(:groups, nil)
  ccr = external_parameters.fetch(:ccr, nil)
  component_version = external_parameters.fetch(:component_version, nil)
  component_name = external_parameters.fetch(:component_name, nil)
  template_name = external_parameters.fetch(:template_name, nil)
  template_version = external_parameters.fetch(:template_version, nil)
  description = external_parameters.fetch(:description, nil)
  lambda_metadata = external_parameters.fetch(:lambda_metadata, nil)
```

making `lambda_metadata` and appropriate keys - in this case `ccr` directly available in the template

2. As for distribution, i suggest following
- we ship new version with cfndsl 1.0.1
- we keep old version as is

This way, components compile both with new and old versions. As suggested, we can add option to disable legacy cfndsl syntax in the future, though leaving it in there won't break anything, it will just introduce those local variables. 

As for the spec file, we could definitely support requiring specific version from the component, looking at the https://github.com/cfndsl/cfndsl/blob/master/lib/cfndsl/runner.rb#L59 
and
https://github.com/cfndsl/cfndsl/blob/master/lib/cfndsl/runner.rb#L94

**Comment by Guslington** [comment]
@toshke seeing some issue with the lambda_metadata when using the lambda helper. Just trying to debug it further but from the generated config the values are set to an empty hash.

```yaml
lambda_metadata:
  path: {}
  sha256: {}
  version: {}
```

**Comment by toshke** [comment]
@Guslington I've updated the PR according to your work in https://github.com/theonestack/cfhighlander/pull/138/files, and it looks like it's working on your example. One thing to consider though is - how come the PR build has passed if this broke, do we hold any lambda - enabled components in test scenarios?

**Comment by Guslington** [comment]
@toshke there are components we are testing that have lambdas however the issue is only when a component is used within a project. `cftest` didn't pickup the issue as it's testing a component as it is, not in the context of a project.

cloning https://github.com/theonestack/hl-component-amazonmq and running `cftest` passes.

where as running `cfcompile` on the following project fails

```rb
CfhighlanderTemplate do
  Component name: 'amazonmq', template: 'amazonmq'
end
```

**Comment by toshke** [comment]
Tested with amazonmq example as well, all good. Perhaps with tests, we should include a test where component is wrapped within outer/parent component for each of the tested ones?

**Pull request merged**
